using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

internal static class YusWorkflowBlackboardKeysGenerator
{
    private const string OutputFolder = "Assets/YusGameFrame/YusWorkflow/Generated/Runtime";

    public static void GenerateFor(YusWorkflowAsset asset)
    {
        if (asset == null) return;

        var keys = CollectKeys(asset);
        var className = ToSafeIdentifier(asset.name) + "BlackboardKeys";
        var fileName = className + ".g.cs";
        var outputPath = Path.Combine(OutputFolder, fileName).Replace('\\', '/');

        Directory.CreateDirectory(OutputFolder);
        File.WriteAllText(outputPath, BuildSource(className, keys), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        AssetDatabase.ImportAsset(outputPath, ImportAssetOptions.ForceUpdate);
    }

    private static List<string> CollectKeys(YusWorkflowAsset asset)
    {
        var list = new List<string>();
        var seen = new HashSet<string>(StringComparer.Ordinal);

        var entries = asset.InitialBlackboard;
        if (entries != null)
        {
            for (var i = 0; i < entries.Count; i++)
            {
                var entry = entries[i];
                if (entry == null) continue;
                if (string.IsNullOrWhiteSpace(entry.Key)) continue;
                var key = entry.Key.Trim();
                if (seen.Add(key)) list.Add(key);
            }
        }

        list.Sort(StringComparer.Ordinal);
        return list;
    }

    private static string BuildSource(string className, IReadOnlyList<string> keys)
    {
        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.Append("public static class ").Append(className).AppendLine();
        sb.AppendLine("{");

        for (var i = 0; i < keys.Count; i++)
        {
            var key = keys[i];
            var constName = ToConstName(key);
            constName = MakeUnique(constName, usedNames);
            sb.Append("    public const string ").Append(constName).Append(" = ").Append(ToCSharpStringLiteral(key)).AppendLine(";");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string MakeUnique(string name, HashSet<string> used)
    {
        if (used.Add(name)) return name;
        var i = 2;
        while (!used.Add(name + "_" + i)) i++;
        return name + "_" + i;
    }

    private static string ToSafeIdentifier(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return "Workflow";
        raw = raw.Trim();

        var sb = new StringBuilder(raw.Length);
        for (var i = 0; i < raw.Length; i++)
        {
            var c = raw[i];
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        var s = sb.ToString();
        if (char.IsDigit(s[0])) s = "_" + s;
        return s;
    }

    private static string ToConstName(string key)
    {
        // "vm:item" -> "Vm_Item"
        if (string.IsNullOrWhiteSpace(key)) return "Key";
        var parts = SplitKey(key);
        if (parts.Count == 0) return "Key";

        var sb = new StringBuilder();
        for (var i = 0; i < parts.Count; i++)
        {
            if (i > 0) sb.Append('_');
            sb.Append(ToPascal(parts[i]));
        }

        var s = sb.ToString();
        if (string.IsNullOrEmpty(s)) s = "Key";
        if (char.IsDigit(s[0])) s = "_" + s;
        return s;
    }

    private static List<string> SplitKey(string key)
    {
        var parts = new List<string>();
        var current = new StringBuilder();

        for (var i = 0; i < key.Length; i++)
        {
            var c = key[i];
            if (char.IsLetterOrDigit(c))
            {
                current.Append(c);
                continue;
            }

            if (current.Length > 0)
            {
                parts.Add(current.ToString());
                current.Length = 0;
            }
        }

        if (current.Length > 0) parts.Add(current.ToString());
        return parts;
    }

    private static string ToPascal(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        if (s.Length == 1) return s.ToUpperInvariant();
        return char.ToUpperInvariant(s[0]) + s.Substring(1);
    }

    private static string ToCSharpStringLiteral(string value)
    {
        if (value == null) return "null";
        return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
