using UnityEngine;

// <auto-generated>
// Generated by YusAnimFSMGenerator (legacy output).
// </auto-generated>

public static class WarriorAnimHash
{
    // Animator state hashes (by state name; generated from AnimatorController).
    // Base_Layer/Attack
    public const int Attack = 1080829965;

    // Base_Layer/Idle
    public const int Idle = 2081823275;

    // Base_Layer/Run
    public const int Run = 1748754976;

}
