using UnityEngine;

// <auto-generated>
// Generated by YusAnimFSMGenerator (legacy output).
// </auto-generated>

[RequireComponent(typeof(Animator))]
public partial class WarriorController : MonoBehaviour
{
    public YusFSM<WarriorController> fsm;
    public Animator Animator { get; private set; }

    [Header("AnimSystem")]
    [SerializeField] private float defaultCrossFadeDuration = 0.1f;
    public float DefaultCrossFadeDuration => defaultCrossFadeDuration;

    private void Awake()
    {
        Animator = GetComponent<Animator>();
        fsm = new YusFSM<WarriorController>(this);
        OnInit();
    }

    private void Update() => fsm.OnUpdate();
    private void FixedUpdate() => fsm.OnFixedUpdate();
    partial void OnInit();
}

// State Base_Layer/Attack
public partial class WarriorAttackState : YusState<WarriorController>
{
    public override void OnEnter()
    {
        owner.Animator.CrossFade(WarriorAnimHash.Attack, owner.DefaultCrossFadeDuration);
        OnEnterUser();
    }

    partial void OnEnterUser();
    public override void OnUpdate() { OnUpdateUser(); }
    partial void OnUpdateUser();
}

// State Base_Layer/Idle
public partial class WarriorIdleState : YusState<WarriorController>
{
    public override void OnEnter()
    {
        owner.Animator.CrossFade(WarriorAnimHash.Idle, owner.DefaultCrossFadeDuration);
        OnEnterUser();
    }

    partial void OnEnterUser();
    public override void OnUpdate() { OnUpdateUser(); }
    partial void OnUpdateUser();
}

// State Base_Layer/Run
public partial class WarriorRunState : YusState<WarriorController>
{
    public override void OnEnter()
    {
        owner.Animator.CrossFade(WarriorAnimHash.Run, owner.DefaultCrossFadeDuration);
        OnEnterUser();
    }

    partial void OnEnterUser();
    public override void OnUpdate() { OnUpdateUser(); }
    partial void OnUpdateUser();
}

